# -*- coding: utf-8 -*-
"""Day 25 - Leetcode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zNe6XPe8zNNq65LIR9gstRqretWctSN7

Leetcode #150 - Evaluate Reverse Polish Notation
"""

class Solution:
    def evalRPN(self, tokens: List[str]) -> int:
        stack = []

        for token in tokens:
            if token in "+-*/":
                b = stack.pop()
                a = stack.pop()

                if token == "+":
                    stack.append(a + b)
                elif token == "-":
                    stack.append(a - b)
                elif token == "*":
                    stack.append(a * b)
                elif token == "/":
                    stack.append(int(a / b))
            else:
                stack.append(int(token))

        return stack[0]