# -*- coding: utf-8 -*-
"""Day 29 -  Leetcode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N0HKJ040hrZyreafrTtjNQ9PogO_ei_M

Leetcode #645 - Set Mismatch
"""

class Solution:
    def findErrorNums(self, nums: List[int]) -> List[int]:
        n = len(nums)
        expected_sum = n * (n + 1) // 2
        set_sum = sum(set(nums))
        actual_sum = sum(nums)

        return [actual_sum - set_sum, expected_sum - set_sum]