# -*- coding: utf-8 -*-
"""Longest Consecutive Sequence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1snL-f_WppB9uCXuZiuWR85dGaZ5BccSw

Leetcode #128 - Longest Consecutive Sequence
"""

class Solution:
    def longestConsecutive(self, nums: List[int]) -> int:
        if not nums:
            return 0
        nums_set=set(nums)
        longest=0
        for num in nums_set:
            if num-1 not in nums_set:
                current = num
                length = 1
                while current+1 in nums_set:
                    current+=1
                    length+=1
                longest=max(longest,length)
        return longest