# -*- coding: utf-8 -*-
"""Leetcode Day5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q61w4JmyXu1ZvwADmhWj_BS4F5_O8pOx

Leet Code #167 - Two Sum II - Input Array Is Sorted
"""

class Solution:
    def twoSum(self, numbers: List[int], target: int) -> List[int]:
        main = {}

        for i in range(len(numbers)):
            diff = target - numbers[i]
            if diff in main:
                return [main[diff]+1, i+1]
            main[numbers[i]] = i

"""Leetcode #349 - Intersection of Two Arrays"""

class Solution:
    def intersection(self, nums1: List[int], nums2: List[int]) -> List[int]:
        nums1_set = set(nums1)
        nums2_set = set(nums2)
        result=[]
        for num in nums1_set:
            if num in nums2_set:
                result.append(num)
        return result