# -*- coding: utf-8 -*-
"""Day 12 - Leetcode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CYGTMdImsitJ9zgiuWvd6GoNeWh5SyoC

Leetcode #56 - Merge Intervals
"""

class Solution:
    def merge(self, intervals: list[list[int]]) -> list[list[int]]:
        # Sort by the start time
        intervals.sort(key=lambda x: x[0])

        merged = []
        for interval in intervals:
            # If the list of merged intervals is empty or
            # if the current interval does not overlap with the previous, append it.
            if not merged or interval[0] > merged[-1][1]:
                merged.append(interval)
            else:
                # Otherwise, there is an overlap, so merge the current and previous intervals.
                merged[-1][1] = max(merged[-1][1], interval[1])

        return merged