# -*- coding: utf-8 -*-
"""Leetcode Day 15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fU22qSWeGT30EDez3X9qCFss0EGDh4St

Leetcode #75 - Sort Colors
"""

class Solution:
    def sortColors(self, nums: List[int]) -> None:
        low = 0
        mid = 0
        high = len(nums) - 1

        while mid <= high:
            if nums[mid] == 0:
                nums[low], nums[mid] = nums[mid], nums[low]
                low += 1
                mid += 1
            elif nums[mid] == 1:
                mid += 1
            else:
                nums[mid], nums[high] = nums[high], nums[mid]
                high -=1