# -*- coding: utf-8 -*-
"""Day 31 - Leetcode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MLyPR17qX8OYIGiWJ-lxz7qDufk5DMjY
"""

class Solution:
    def findErrorNums(self, nums: List[int]) -> List[int]:
        s=set()
        duplicate = 0
        missing = 0
        s=set()
        for i in range(len(nums)):
            val=nums[i]
            if nums[i] not in s:
                s.add(val)
            else:
                duplicate = val
        for i in range(1,len(nums)+1):
            if i not in s:
                missing=i
        return(duplicate,missing)