# -*- coding: utf-8 -*-
"""Day 10 - Leetcode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EKui3hsOzyVSrp9KkoGfz6uMiwuCCBpR

Leetcode #153 - Find Minimum in Rotated Sorted Array
"""

class Solution:
    def findMin(self, nums: List[int]) -> int:
        left=0
        right=len(nums)-1
        while(left<right):
            mid=(left+right)//2
            if(nums[mid]>nums[right]):
                left=mid+1
            else:
                right=mid

        return nums[left]