# -*- coding: utf-8 -*-
"""Leetcode#169 - Day 26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aMhL5pDP0iJm-CefBaRV9J8YkqWagb-P

Leetcode #169 - Majority Element
"""

class Solution:
    def majorityElement(self, nums: List[int]) -> int:
        dict={}
        maximum=0
        for num in nums:
            if num not in dict:
                dict[num]=1
            else:
                dict[num]+=1
        for i in dict:
            maximum=max(maximum,dict[i])
            if maximum>(len(nums)/2):
                return i