# -*- coding: utf-8 -*-
"""Leetcode Day 26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aMhL5pDP0iJm-CefBaRV9J8YkqWagb-P

Leetcode #1512 - Number of Good Pairs(Brute force)
"""

class Solution:
    def numIdenticalPairs(self, nums: List[int]) -> int:
        count=0
        for i in range(len(nums)):
            for j in range(i+1,len(nums)):
                if((nums[i]==nums[j])):
                    count+=1
        return count

"""Leetcode #1512 - Number of Good Pairs(Using Hashmaps)"""

class Solution:
    def numIdenticalPairs(self, nums: List[int]) -> int:
        dict={}
        sum=0
        for num in nums:
            if num not in dict:
                dict[num]=1
            else:
                dict[num]+=1
        for num in dict:
            n=dict[num]
            sum+=int(n*(n-1)/2)
        return int(sum)