# -*- coding: utf-8 -*-
"""Day 28 -  Leetcode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N0HKJ040hrZyreafrTtjNQ9PogO_ei_M

Leetcode #205 - Isomorphic Strings
"""

class Solution:
    def isIsomorphic(self, s: str, t: str) -> bool:
        # If lengths differ, they can't be isomorphic
        if len(s) != len(t):
            return False

        map_st, map_ts = {}, {}

        for char_s, char_t in zip(s, t):
            # Check mapping from s -> t
            if char_s in map_st and map_st[char_s] != char_t:
                return False

            # Check mapping from t -> s
            if char_t in map_ts and map_ts[char_t] != char_s:
                return False

            # Establish the mapping
            map_st[char_s] = char_t
            map_ts[char_t] = char_s

        return True