# -*- coding: utf-8 -*-
"""Leetcode  - Day 17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/184H-R_KTlo6A95slgVlJmij6rFTfDuVX

Leetcode #20 - Valid Parentheses
"""

class Solution:
    def isValid(self, s: str) -> bool:
           stack=[]
           closeToOpen = { ")":"(", "]":"[", "}":"{" }

           for c in s:
                if c in closeToOpen:
                    if stack and stack[-1]==closeToOpen[c]:
                        stack.pop()
                    else:
                        return False
                else:
                    stack.append(c)
           return True if not stack else False